### ISSUE TITLE
Missing types.d.ts (TypeScript Support)

### ISSUE THREAD

**Issue by gomes042** [junminahn/node-font2base64#3]

**Comment by junminahn** [comment]
@runtothedoor sorry for the late response; providing type information files is on the backlog item, so I will work on it as time allowed for myself. thanks!

**Comment by junminahn** [comment]
@runtothedoor please try `node-font2base64@0.9.2` for the new version that includes the type declaration and `esm` support. https://www.npmjs.com/package/node-font2base64

Thanks again for the contribution.
